export const mock14Days = {
  state: 'Andhra Pradesh',
  cases: 8452,
  deaths: 101,
  historical: [
    {
      date: '3/14/20',
      cases: 1,
      deaths: 0,
      recovered: 0,
    },
    {
      date: '3/15/20',
      cases: 1,
      deaths: 0,
      recovered: 0,
    },
    {
      date: '3/16/20',
      cases: 1,
      deaths: 0,
      recovered: 0,
    },
    {
      date: '3/17/20',
      cases: 1,
      deaths: 0,
      recovered: 0,
    },
    {
      date: '3/18/20',
      cases: 1,
      deaths: 0,
      recovered: 0,
    },
    {
      date: '3/19/20',
      cases: 3,
      deaths: 0,
      recovered: 0,
    },
    {
      date: '3/20/20',
      cases: 3,
      deaths: 0,
      recovered: 0,
    },
    {
      date: '3/21/20',
      cases: 5,
      deaths: 0,
      recovered: 0,
    },
    {
      date: '3/22/20',
      cases: 6,
      deaths: 0,
      recovered: 0,
    },
    {
      date: '3/23/20',
      cases: 7,
      deaths: 0,
      recovered: 0,
    },
    {
      date: '3/24/20',
      cases: 8,
      deaths: 0,
      recovered: 0,
    },
    {
      date: '3/25/20',
      cases: 10,
      deaths: 0,
      recovered: 1,
    },
    {
      date: '3/26/20',
      cases: 11,
      deaths: 0,
      recovered: 1,
    },
    {
      date: '3/27/20',
      cases: 13,
      deaths: 0,
      recovered: 1,
    },
  ],
  districts: [
    {
      district: 'Foreign Evacuees',
      cases: 326,
      active: 277,
      deaths: 0,
      recovered: 49,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '5/25/20',
          cases: 62,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/26/20',
          cases: 111,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/27/20',
          cases: 111,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/28/20',
          cases: 111,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/29/20',
          cases: 111,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/30/20',
          cases: 111,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/31/20',
          cases: 111,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '6/1/20',
          cases: 112,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '6/2/20',
          cases: 112,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '6/3/20',
          cases: 119,
          deaths: 0,
          recovered: 1,
        },
        {
          date: '6/4/20',
          cases: 119,
          deaths: 0,
          recovered: 4,
        },
        {
          date: '6/5/20',
          cases: 123,
          deaths: 0,
          recovered: 4,
        },
        {
          date: '6/6/20',
          cases: 131,
          deaths: 0,
          recovered: 4,
        },
        {
          date: '6/7/20',
          cases: 131,
          deaths: 0,
          recovered: 5,
        },
      ],
    },
    {
      district: 'Anantapur',
      cases: 789,
      active: 553,
      deaths: 6,
      recovered: 230,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '4/21/20',
          cases: 36,
          deaths: 3,
          recovered: 2,
        },
        {
          date: '4/22/20',
          cases: 36,
          deaths: 3,
          recovered: 2,
        },
        {
          date: '4/23/20',
          cases: 42,
          deaths: 3,
          recovered: 7,
        },
        {
          date: '4/24/20',
          cases: 46,
          deaths: 4,
          recovered: 11,
        },
        {
          date: '4/25/20',
          cases: 51,
          deaths: 4,
          recovered: 13,
        },
        {
          date: '4/26/20',
          cases: 53,
          deaths: 4,
          recovered: 14,
        },
        {
          date: '4/27/20',
          cases: 53,
          deaths: 4,
          recovered: 14,
        },
        {
          date: '4/28/20',
          cases: 54,
          deaths: 4,
          recovered: 14,
        },
        {
          date: '4/29/20',
          cases: 58,
          deaths: 4,
          recovered: 17,
        },
        {
          date: '4/30/20',
          cases: 61,
          deaths: 4,
          recovered: 20,
        },
        {
          date: '5/1/20',
          cases: 67,
          deaths: 4,
          recovered: 22,
        },
        {
          date: '5/2/20',
          cases: 71,
          deaths: 4,
          recovered: 24,
        },
        {
          date: '5/3/20',
          cases: 78,
          deaths: 4,
          recovered: 24,
        },
        {
          date: '5/4/20',
          cases: 78,
          deaths: 4,
          recovered: 24,
        },
      ],
    },
    {
      district: 'Chittoor',
      cases: 515,
      active: 242,
      deaths: 5,
      recovered: 268,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '4/21/20',
          cases: 53,
          deaths: 0,
          recovered: 4,
        },
        {
          date: '4/22/20',
          cases: 59,
          deaths: 0,
          recovered: 4,
        },
        {
          date: '4/23/20',
          cases: 73,
          deaths: 0,
          recovered: 11,
        },
        {
          date: '4/24/20',
          cases: 73,
          deaths: 0,
          recovered: 11,
        },
        {
          date: '4/25/20',
          cases: 73,
          deaths: 0,
          recovered: 11,
        },
        {
          date: '4/26/20',
          cases: 73,
          deaths: 0,
          recovered: 13,
        },
        {
          date: '4/27/20',
          cases: 73,
          deaths: 0,
          recovered: 16,
        },
        {
          date: '4/28/20',
          cases: 74,
          deaths: 0,
          recovered: 16,
        },
        {
          date: '4/29/20',
          cases: 77,
          deaths: 0,
          recovered: 16,
        },
        {
          date: '4/30/20',
          cases: 80,
          deaths: 0,
          recovered: 16,
        },
        {
          date: '5/1/20',
          cases: 80,
          deaths: 0,
          recovered: 22,
        },
        {
          date: '5/2/20',
          cases: 80,
          deaths: 0,
          recovered: 24,
        },
        {
          date: '5/3/20',
          cases: 81,
          deaths: 0,
          recovered: 37,
        },
        {
          date: '5/4/20',
          cases: 82,
          deaths: 0,
          recovered: 45,
        },
      ],
    },
    {
      district: 'East Godavari',
      cases: 485,
      active: 213,
      deaths: 5,
      recovered: 267,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '4/21/20',
          cases: 26,
          deaths: 0,
          recovered: 8,
        },
        {
          date: '4/22/20',
          cases: 26,
          deaths: 0,
          recovered: 8,
        },
        {
          date: '4/23/20',
          cases: 32,
          deaths: 0,
          recovered: 8,
        },
        {
          date: '4/24/20',
          cases: 34,
          deaths: 0,
          recovered: 8,
        },
        {
          date: '4/25/20',
          cases: 37,
          deaths: 0,
          recovered: 12,
        },
        {
          date: '4/26/20',
          cases: 39,
          deaths: 0,
          recovered: 12,
        },
        {
          date: '4/27/20',
          cases: 39,
          deaths: 0,
          recovered: 12,
        },
        {
          date: '4/28/20',
          cases: 39,
          deaths: 0,
          recovered: 12,
        },
        {
          date: '4/29/20',
          cases: 40,
          deaths: 0,
          recovered: 12,
        },
        {
          date: '4/30/20',
          cases: 42,
          deaths: 0,
          recovered: 14,
        },
        {
          date: '5/1/20',
          cases: 42,
          deaths: 0,
          recovered: 17,
        },
        {
          date: '5/2/20',
          cases: 45,
          deaths: 0,
          recovered: 17,
        },
        {
          date: '5/3/20',
          cases: 45,
          deaths: 0,
          recovered: 20,
        },
        {
          date: '5/4/20',
          cases: 45,
          deaths: 0,
          recovered: 22,
        },
      ],
    },
    {
      district: 'Guntur',
      cases: 742,
      active: 238,
      deaths: 11,
      recovered: 493,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '4/21/20',
          cases: 157,
          deaths: 6,
          recovered: 15,
        },
        {
          date: '4/22/20',
          cases: 177,
          deaths: 6,
          recovered: 15,
        },
        {
          date: '4/23/20',
          cases: 195,
          deaths: 8,
          recovered: 23,
        },
        {
          date: '4/24/20',
          cases: 206,
          deaths: 8,
          recovered: 23,
        },
        {
          date: '4/25/20',
          cases: 209,
          deaths: 8,
          recovered: 23,
        },
        {
          date: '4/26/20',
          cases: 214,
          deaths: 8,
          recovered: 29,
        },
        {
          date: '4/27/20',
          cases: 237,
          deaths: 8,
          recovered: 29,
        },
        {
          date: '4/28/20',
          cases: 254,
          deaths: 8,
          recovered: 39,
        },
        {
          date: '4/29/20',
          cases: 283,
          deaths: 8,
          recovered: 59,
        },
        {
          date: '4/30/20',
          cases: 287,
          deaths: 8,
          recovered: 87,
        },
        {
          date: '5/1/20',
          cases: 306,
          deaths: 8,
          recovered: 97,
        },
        {
          date: '5/2/20',
          cases: 308,
          deaths: 8,
          recovered: 97,
        },
        {
          date: '5/3/20',
          cases: 319,
          deaths: 8,
          recovered: 115,
        },
        {
          date: '5/4/20',
          cases: 338,
          deaths: 8,
          recovered: 115,
        },
      ],
    },
    {
      district: 'Krishna',
      cases: 982,
      active: 521,
      deaths: 33,
      recovered: 428,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '4/21/20',
          cases: 83,
          deaths: 6,
          recovered: 14,
        },
        {
          date: '4/22/20',
          cases: 86,
          deaths: 6,
          recovered: 14,
        },
        {
          date: '4/23/20',
          cases: 88,
          deaths: 7,
          recovered: 25,
        },
        {
          date: '4/24/20',
          cases: 102,
          deaths: 7,
          recovered: 25,
        },
        {
          date: '4/25/20',
          cases: 127,
          deaths: 8,
          recovered: 29,
        },
        {
          date: '4/26/20',
          cases: 177,
          deaths: 8,
          recovered: 29,
        },
        {
          date: '4/27/20',
          cases: 210,
          deaths: 8,
          recovered: 29,
        },
        {
          date: '4/28/20',
          cases: 223,
          deaths: 8,
          recovered: 29,
        },
        {
          date: '4/29/20',
          cases: 236,
          deaths: 8,
          recovered: 32,
        },
        {
          date: '4/30/20',
          cases: 246,
          deaths: 8,
          recovered: 32,
        },
        {
          date: '5/1/20',
          cases: 246,
          deaths: 8,
          recovered: 37,
        },
        {
          date: '5/2/20',
          cases: 258,
          deaths: 8,
          recovered: 44,
        },
        {
          date: '5/3/20',
          cases: 266,
          deaths: 8,
          recovered: 46,
        },
        {
          date: '5/4/20',
          cases: 278,
          deaths: 8,
          recovered: 46,
        },
      ],
    },
    {
      district: 'Kurnool',
      cases: 1247,
      active: 485,
      deaths: 33,
      recovered: 729,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '4/21/20',
          cases: 184,
          deaths: 5,
          recovered: 4,
        },
        {
          date: '4/22/20',
          cases: 203,
          deaths: 5,
          recovered: 4,
        },
        {
          date: '4/23/20',
          cases: 234,
          deaths: 7,
          recovered: 4,
        },
        {
          date: '4/24/20',
          cases: 261,
          deaths: 8,
          recovered: 4,
        },
        {
          date: '4/25/20',
          cases: 275,
          deaths: 9,
          recovered: 7,
        },
        {
          date: '4/26/20',
          cases: 279,
          deaths: 9,
          recovered: 31,
        },
        {
          date: '4/27/20',
          cases: 292,
          deaths: 9,
          recovered: 31,
        },
        {
          date: '4/28/20',
          cases: 332,
          deaths: 9,
          recovered: 43,
        },
        {
          date: '4/29/20',
          cases: 343,
          deaths: 9,
          recovered: 43,
        },
        {
          date: '4/30/20',
          cases: 386,
          deaths: 9,
          recovered: 43,
        },
        {
          date: '5/1/20',
          cases: 411,
          deaths: 10,
          recovered: 66,
        },
        {
          date: '5/2/20',
          cases: 436,
          deaths: 10,
          recovered: 66,
        },
        {
          date: '5/3/20',
          cases: 466,
          deaths: 10,
          recovered: 77,
        },
        {
          date: '5/4/20',
          cases: 491,
          deaths: 10,
          recovered: 86,
        },
      ],
    },
    {
      district: 'Other State',
      cases: 1506,
      active: 647,
      deaths: 0,
      recovered: 859,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '5/5/20',
          cases: 14,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/6/20',
          cases: 27,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/7/20',
          cases: 27,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/8/20',
          cases: 27,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/9/20',
          cases: 27,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/10/20',
          cases: 27,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/11/20',
          cases: 27,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/12/20',
          cases: 27,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/13/20',
          cases: 73,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/14/20',
          cases: 105,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/15/20',
          cases: 150,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/16/20',
          cases: 150,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/17/20',
          cases: 150,
          deaths: 0,
          recovered: 23,
        },
        {
          date: '5/18/20',
          cases: 150,
          deaths: 0,
          recovered: 25,
        },
      ],
    },
    {
      district: 'Prakasam',
      cases: 175,
      active: 78,
      deaths: 2,
      recovered: 95,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '4/21/20',
          cases: 44,
          deaths: 0,
          recovered: 1,
        },
        {
          date: '4/22/20',
          cases: 48,
          deaths: 0,
          recovered: 1,
        },
        {
          date: '4/23/20',
          cases: 50,
          deaths: 0,
          recovered: 1,
        },
        {
          date: '4/24/20',
          cases: 53,
          deaths: 0,
          recovered: 1,
        },
        {
          date: '4/25/20',
          cases: 53,
          deaths: 0,
          recovered: 12,
        },
        {
          date: '4/26/20',
          cases: 56,
          deaths: 0,
          recovered: 23,
        },
        {
          date: '4/27/20',
          cases: 56,
          deaths: 0,
          recovered: 23,
        },
        {
          date: '4/28/20',
          cases: 56,
          deaths: 0,
          recovered: 23,
        },
        {
          date: '4/29/20',
          cases: 60,
          deaths: 0,
          recovered: 23,
        },
        {
          date: '4/30/20',
          cases: 60,
          deaths: 0,
          recovered: 23,
        },
        {
          date: '5/1/20',
          cases: 60,
          deaths: 0,
          recovered: 23,
        },
        {
          date: '5/2/20',
          cases: 61,
          deaths: 0,
          recovered: 42,
        },
        {
          date: '5/3/20',
          cases: 61,
          deaths: 0,
          recovered: 42,
        },
        {
          date: '5/4/20',
          cases: 61,
          deaths: 0,
          recovered: 50,
        },
      ],
    },
    {
      district: 'S.P.S. Nellore',
      cases: 459,
      active: 213,
      deaths: 4,
      recovered: 242,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '4/21/20',
          cases: 68,
          deaths: 2,
          recovered: 2,
        },
        {
          date: '4/22/20',
          cases: 67,
          deaths: 2,
          recovered: 2,
        },
        {
          date: '4/23/20',
          cases: 67,
          deaths: 2,
          recovered: 6,
        },
        {
          date: '4/24/20',
          cases: 68,
          deaths: 2,
          recovered: 6,
        },
        {
          date: '4/25/20',
          cases: 72,
          deaths: 2,
          recovered: 8,
        },
        {
          date: '4/26/20',
          cases: 72,
          deaths: 2,
          recovered: 23,
        },
        {
          date: '4/27/20',
          cases: 79,
          deaths: 2,
          recovered: 23,
        },
        {
          date: '4/28/20',
          cases: 82,
          deaths: 2,
          recovered: 24,
        },
        {
          date: '4/29/20',
          cases: 82,
          deaths: 2,
          recovered: 27,
        },
        {
          date: '4/30/20',
          cases: 84,
          deaths: 2,
          recovered: 27,
        },
        {
          date: '5/1/20',
          cases: 84,
          deaths: 3,
          recovered: 43,
        },
        {
          date: '5/2/20',
          cases: 90,
          deaths: 3,
          recovered: 44,
        },
        {
          date: '5/3/20',
          cases: 91,
          deaths: 3,
          recovered: 44,
        },
        {
          date: '5/4/20',
          cases: 91,
          deaths: 3,
          recovered: 50,
        },
      ],
    },
    {
      district: 'Srikakulam',
      cases: 59,
      active: 36,
      deaths: 1,
      recovered: 22,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '4/25/20',
          cases: 3,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '4/26/20',
          cases: 3,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '4/27/20',
          cases: 4,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '4/28/20',
          cases: 4,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '4/29/20',
          cases: 5,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '4/30/20',
          cases: 5,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/1/20',
          cases: 5,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/2/20',
          cases: 5,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/3/20',
          cases: 5,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/4/20',
          cases: 5,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/5/20',
          cases: 5,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/6/20',
          cases: 5,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/7/20',
          cases: 5,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/8/20',
          cases: 5,
          deaths: 0,
          recovered: 0,
        },
      ],
    },
    {
      district: 'Visakhapatnam',
      cases: 261,
      active: 109,
      deaths: 1,
      recovered: 151,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '4/21/20',
          cases: 21,
          deaths: 0,
          recovered: 18,
        },
        {
          date: '4/22/20',
          cases: 21,
          deaths: 0,
          recovered: 18,
        },
        {
          date: '4/23/20',
          cases: 22,
          deaths: 0,
          recovered: 19,
        },
        {
          date: '4/24/20',
          cases: 22,
          deaths: 0,
          recovered: 19,
        },
        {
          date: '4/25/20',
          cases: 22,
          deaths: 0,
          recovered: 19,
        },
        {
          date: '4/26/20',
          cases: 22,
          deaths: 0,
          recovered: 19,
        },
        {
          date: '4/27/20',
          cases: 22,
          deaths: 0,
          recovered: 19,
        },
        {
          date: '4/28/20',
          cases: 22,
          deaths: 0,
          recovered: 19,
        },
        {
          date: '4/29/20',
          cases: 23,
          deaths: 0,
          recovered: 19,
        },
        {
          date: '4/30/20',
          cases: 23,
          deaths: 0,
          recovered: 20,
        },
        {
          date: '5/1/20',
          cases: 25,
          deaths: 0,
          recovered: 20,
        },
        {
          date: '5/2/20',
          cases: 29,
          deaths: 0,
          recovered: 20,
        },
        {
          date: '5/3/20',
          cases: 29,
          deaths: 0,
          recovered: 20,
        },
        {
          date: '5/4/20',
          cases: 35,
          deaths: 0,
          recovered: 20,
        },
      ],
    },
    {
      district: 'Vizianagaram',
      cases: 78,
      active: 47,
      deaths: 0,
      recovered: 31,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '5/7/20',
          cases: 3,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/8/20',
          cases: 4,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/9/20',
          cases: 4,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/10/20',
          cases: 4,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/11/20',
          cases: 4,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/12/20',
          cases: 4,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/13/20',
          cases: 4,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/14/20',
          cases: 4,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/15/20',
          cases: 7,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/16/20',
          cases: 7,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/17/20',
          cases: 7,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/18/20',
          cases: 8,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/19/20',
          cases: 8,
          deaths: 0,
          recovered: 0,
        },
        {
          date: '5/20/20',
          cases: 16,
          deaths: 0,
          recovered: 4,
        },
      ],
    },
    {
      district: 'West Godavari',
      cases: 498,
      active: 393,
      deaths: 0,
      recovered: 105,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '4/21/20',
          cases: 39,
          deaths: 0,
          recovered: 9,
        },
        {
          date: '4/22/20',
          cases: 39,
          deaths: 0,
          recovered: 9,
        },
        {
          date: '4/23/20',
          cases: 39,
          deaths: 0,
          recovered: 9,
        },
        {
          date: '4/24/20',
          cases: 39,
          deaths: 0,
          recovered: 9,
        },
        {
          date: '4/25/20',
          cases: 39,
          deaths: 0,
          recovered: 9,
        },
        {
          date: '4/26/20',
          cases: 51,
          deaths: 0,
          recovered: 10,
        },
        {
          date: '4/27/20',
          cases: 54,
          deaths: 0,
          recovered: 11,
        },
        {
          date: '4/28/20',
          cases: 54,
          deaths: 0,
          recovered: 11,
        },
        {
          date: '4/29/20',
          cases: 56,
          deaths: 0,
          recovered: 11,
        },
        {
          date: '4/30/20',
          cases: 56,
          deaths: 0,
          recovered: 11,
        },
        {
          date: '5/1/20',
          cases: 58,
          deaths: 0,
          recovered: 19,
        },
        {
          date: '5/2/20',
          cases: 59,
          deaths: 0,
          recovered: 26,
        },
        {
          date: '5/3/20',
          cases: 59,
          deaths: 0,
          recovered: 26,
        },
        {
          date: '5/4/20',
          cases: 59,
          deaths: 0,
          recovered: 29,
        },
      ],
    },
    {
      district: 'Y.S.R. Kadapa',
      cases: 330,
      active: 188,
      deaths: 0,
      recovered: 142,
      todayCases: 0,
      todayDeaths: 0,
      todayRecovered: 0,
      historical: [
        {
          date: '5/3/20',
          cases: 83,
          deaths: 0,
          recovered: 37,
        },
        {
          date: '5/4/20',
          cases: 87,
          deaths: 0,
          recovered: 37,
        },
        {
          date: '5/5/20',
          cases: 89,
          deaths: 0,
          recovered: 39,
        },
        {
          date: '5/6/20',
          cases: 90,
          deaths: 0,
          recovered: 40,
        },
        {
          date: '5/7/20',
          cases: 96,
          deaths: 0,
          recovered: 40,
        },
        {
          date: '5/8/20',
          cases: 96,
          deaths: 0,
          recovered: 43,
        },
        {
          date: '5/9/20',
          cases: 96,
          deaths: 0,
          recovered: 43,
        },
        {
          date: '5/10/20',
          cases: 97,
          deaths: 0,
          recovered: 43,
        },
        {
          date: '5/11/20',
          cases: 97,
          deaths: 0,
          recovered: 45,
        },
        {
          date: '5/12/20',
          cases: 97,
          deaths: 0,
          recovered: 46,
        },
        {
          date: '5/13/20',
          cases: 97,
          deaths: 0,
          recovered: 56,
        },
        {
          date: '5/14/20',
          cases: 99,
          deaths: 0,
          recovered: 56,
        },
        {
          date: '5/15/20',
          cases: 101,
          deaths: 0,
          recovered: 63,
        },
        {
          date: '5/16/20',
          cases: 102,
          deaths: 0,
          recovered: 65,
        },
      ],
    },
  ],
};
